const kanjiData = [
    { kanji: '日', onyomi: ['ニチ', 'ジツ'], kunyomi: ['ひ', 'か'] },
    { kanji: '月', onyomi: ['ゲツ', 'ガツ'], kunyomi: ['つき'] },
    { kanji: '火', onyomi: ['カ'], kunyomi: ['ひ'] },
    { kanji: '水', onyomi: ['スイ'], kunyomi: ['みず'] },
    { kanji: '木', onyomi: ['モク', 'ボク'], kunyomi: ['き'] },
    { kanji: '金', onyomi: ['キン', 'コン'], kunyomi: ['かね'] },
    { kanji: '土', onyomi: ['ド', 'ト'], kunyomi: ['つち'] },
    { kanji: '人', onyomi: ['ジン', 'ニン'], kunyomi: ['ひと'] },
    { kanji: '山', onyomi: ['サン'], kunyomi: ['やま'] },
    { kanji: '川', onyomi: ['セン'], kunyomi: ['かわ'] },
    { kanji: '田', onyomi: ['デン'], kunyomi: ['た'] },
    { kanji: '目', onyomi: ['モク', 'ボク'], kunyomi: ['め'] },
    { kanji: '手', onyomi: ['シュ'], kunyomi: ['て'] },
    { kanji: '足', onyomi: ['ソク'], kunyomi: ['あし'] },
    { kanji: '口', onyomi: ['コウ', 'ク'], kunyomi: ['くち'] },
    { kanji: '耳', onyomi: ['ジ'], kunyomi: ['みみ'] },
    { kanji: '心', onyomi: ['シン'], kunyomi: ['こころ'] },
    { kanji: '力', onyomi: ['リョク', 'リキ'], kunyomi: ['ちから'] },
    { kanji: '門', onyomi: ['モン'], kunyomi: ['かど'] },
    { kanji: '石', onyomi: ['セキ', 'シャク'], kunyomi: ['いし'] },
    { kanji: '竹', onyomi: ['チク'], kunyomi: ['たけ'] },
    { kanji: '糸', onyomi: ['シ'], kunyomi: ['いと'] },
    { kanji: '貝', onyomi: ['バイ'], kunyomi: ['かい'] },
    { kanji: '車', onyomi: ['シャ'], kunyomi: ['くるま'] },
    { kanji: '雨', onyomi: ['ウ'], kunyomi: ['あめ'] },
    { kanji: '花', onyomi: ['カ'], kunyomi: ['はな'] },
    { kanji: '草', onyomi: ['ソウ'], kunyomi: ['くさ'] },
    { kanji: '虫', onyomi: ['チュウ'], kunyomi: ['むし'] },
    { kanji: '犬', onyomi: ['ケン'], kunyomi: ['いぬ'] },
    { kanji: '魚', onyomi: ['ギョ'], kunyomi: ['さかな'] },
    { kanji: '鳥', onyomi: ['チョウ'], kunyomi: ['とり'] },
    { kanji: '馬', onyomi: ['バ'], kunyomi: ['うま'] },
    { kanji: '牛', onyomi: ['ギュウ'], kunyomi: ['うし'] },
    { kanji: '羊', onyomi: ['ヨウ'], kunyomi: ['ひつじ'] },
    { kanji: '空', onyomi: ['クウ'], kunyomi: ['そら', 'から'] },
    { kanji: '海', onyomi: ['カイ'], kunyomi: ['うみ'] },
    { kanji: '森', onyomi: ['シン'], kunyomi: ['もり'] },
    { kanji: '林', onyomi: ['リン'], kunyomi: ['はやし'] },
    { kanji: '村', onyomi: ['ソン'], kunyomi: ['むら'] },
    { kanji: '町', onyomi: ['チョウ'], kunyomi: ['まち'] },
    { kanji: '学', onyomi: ['ガク'], kunyomi: ['まなぶ'] },
    { kanji: '校', onyomi: ['コウ'], kunyomi: [] },
    { kanji: '先', onyomi: ['セン'], kunyomi: ['さき'] },
    { kanji: '生', onyomi: ['セイ', 'ショウ'], kunyomi: ['いきる', 'うまれる'] },
    { kanji: '年', onyomi: ['ネン'], kunyomi: ['とし'] },
    { kanji: '時', onyomi: ['ジ'], kunyomi: ['とき'] },
    { kanji: '分', onyomi: ['ブン', 'フン'], kunyomi: ['わける'] },
    { kanji: '間', onyomi: ['カン', 'ケン'], kunyomi: ['あいだ', 'ま'] },
    { kanji: '今', onyomi: ['コン', 'キン'], kunyomi: ['いま'] },
    { kanji: '新', onyomi: ['シン'], kunyomi: ['あたらしい'] },
    { kanji: '古', onyomi: ['コ'], kunyomi: ['ふるい'] },
    { kanji: '長', onyomi: ['チョウ'], kunyomi: ['ながい'] },
    { kanji: '短', onyomi: ['タン'], kunyomi: ['みじかい'] },
    { kanji: '高', onyomi: ['コウ'], kunyomi: ['たかい'] },
    { kanji: '低', onyomi: ['テイ'], kunyomi: ['ひくい'] },
    { kanji: '大', onyomi: ['ダイ', 'タイ'], kunyomi: ['おおきい'] },
    { kanji: '小', onyomi: ['ショウ'], kunyomi: ['ちいさい'] },
    { kanji: '多', onyomi: ['タ'], kunyomi: ['おおい'] },
    { kanji: '少', onyomi: ['ショウ'], kunyomi: ['すくない'] },
    { kanji: '明', onyomi: ['メイ', 'ミョウ'], kunyomi: ['あかるい'] },
    { kanji: '暗', onyomi: ['アン'], kunyomi: ['くらい'] },
    { kanji: '白', onyomi: ['ハク', 'ビャク'], kunyomi: ['しろい'] },
    { kanji: '黒', onyomi: ['コク'], kunyomi: ['くろい'] },
    { kanji: '赤', onyomi: ['セキ', 'シャク'], kunyomi: ['あかい'] },
    { kanji: '青', onyomi: ['セイ', 'ショウ'], kunyomi: ['あおい'] },
    { kanji: '色', onyomi: ['シキ', 'ショク'], kunyomi: ['いろ'] },
    { kanji: '音', onyomi: ['オン', 'イン'], kunyomi: ['おと'] },
    { kanji: '声', onyomi: ['セイ', 'ショウ'], kunyomi: ['こえ'] },
    { kanji: '言', onyomi: ['ゲン', 'ゴン'], kunyomi: ['いう', 'こと'] },
    { kanji: '話', onyomi: ['ワ'], kunyomi: ['はなす', 'はなし'] },
    { kanji: '語', onyomi: ['ゴ'], kunyomi: ['かたる'] },
    { kanji: '読', onyomi: ['ドク', 'トク'], kunyomi: ['よむ'] },
    { kanji: '書', onyomi: ['ショ'], kunyomi: ['かく'] },
    { kanji: '見', onyomi: ['ケン'], kunyomi: ['みる'] },
    { kanji: '聞', onyomi: ['ブン', 'モン'], kunyomi: ['きく'] },
    { kanji: '食', onyomi: ['ショク'], kunyomi: ['たべる'] },
    { kanji: '飲', onyomi: ['イン'], kunyomi: ['のむ'] },
    { kanji: '立', onyomi: ['リツ', 'リュウ'], kunyomi: ['たつ'] },
    { kanji: '休', onyomi: ['キュウ'], kunyomi: ['やすむ'] },
    { kanji: '走', onyomi: ['ソウ'], kunyomi: ['はしる'] },
    { kanji: '歩', onyomi: ['ホ', 'ブ'], kunyomi: ['あるく'] },
    { kanji: '来', onyomi: ['ライ'], kunyomi: ['くる'] },
    { kanji: '行', onyomi: ['コウ', 'ギョウ'], kunyomi: ['いく', 'ゆく'] },
    { kanji: '帰', onyomi: ['キ'], kunyomi: ['かえる'] },
    { kanji: '入', onyomi: ['ニュウ'], kunyomi: ['いる', 'はいる'] },
    { kanji: '出', onyomi: ['シュツ'], kunyomi: ['でる'] }
];
