const kanjiData = [
    { kanji: '一', onyomi: ['イチ', 'イツ'], kunyomi: ['ひと', 'ひと.つ'] },
    { kanji: '七', onyomi: ['シチ'], kunyomi: ['なな', 'なな.つ', 'なの'] },
    { kanji: '万', onyomi: ['マン', 'バン'], kunyomi: ['よろず'] },
    { kanji: '三', onyomi: ['サン'], kunyomi: ['み', 'み.つ', 'みっ.つ'] },
    { kanji: '上', onyomi: ['ジョウ', 'ショウ', 'シャン'], kunyomi: ['うえ', 'うわ', 'かみ', 'あ.げる', 'あ.がる', 'のぼ.る'] },
    { kanji: '下', onyomi: ['カ', 'ゲ'], kunyomi: ['した', 'しも', 'もと', 'さ.げる', 'さ.がる', 'くだ.る', 'お.ろす'] },
    { kanji: '不', onyomi: ['フ', 'ブ'], kunyomi: [] },
    { kanji: '世', onyomi: ['セイ', 'セ', 'ソウ'], kunyomi: ['よ'] },
    { kanji: '両', onyomi: ['リョウ'], kunyomi: ['ふた.つ', 'もろ'] },
    { kanji: '中', onyomi: ['チュウ', 'ジュウ'], kunyomi: ['なか', 'うち', 'あた.る'] },
    { kanji: '主', onyomi: ['シュ', 'ス'], kunyomi: ['ぬし', 'おも', 'あるじ'] },
    { kanji: '久', onyomi: ['キュウ', 'ク'], kunyomi: ['ひさ.しい'] },
    { kanji: '乗', onyomi: ['ジョウ', 'ショウ'], kunyomi: ['の.る', 'の.せる'] },
    { kanji: '九', onyomi: ['キュウ', 'ク'], kunyomi: ['ここの', 'ここの.つ'] },
    { kanji: '予', onyomi: ['ヨ', 'シャ'], kunyomi: [] },
    { kanji: '事', onyomi: ['ジ', 'ズ'], kunyomi: ['こと', 'つか.う'] },
    { kanji: '二', onyomi: ['ニ', 'ジ'], kunyomi: ['ふた', 'ふた.つ', 'ふたた.び'] },
    { kanji: '五', onyomi: ['ゴ'], kunyomi: ['いつ', 'いつ.つ'] },
    { kanji: '京', onyomi: ['キョウ', 'ケイ', 'キン'], kunyomi: ['みやこ'] },
    { kanji: '人', onyomi: ['ジン', 'ニン'], kunyomi: ['ひと'] },
    { kanji: '今', onyomi: ['コン', 'キン'], kunyomi: ['いま'] },
    { kanji: '仕', onyomi: ['シ', 'ジ'], kunyomi: ['つか.える'] },
    { kanji: '他', onyomi: ['タ'], kunyomi: ['ほか'] },
    { kanji: '代', onyomi: ['ダイ', 'タイ'], kunyomi: ['か.わる', 'か.える', 'よ', 'しろ'] },
    { kanji: '以', onyomi: ['イ'], kunyomi: ['もっ.て'] },
    { kanji: '会', onyomi: ['カイ', 'エ'], kunyomi: ['あ.う'] },
    { kanji: '体', onyomi: ['タイ', 'テイ'], kunyomi: ['からだ'] },
    { kanji: '作', onyomi: ['サク', 'サ'], kunyomi: ['つく.る'] },
    { kanji: '使', onyomi: ['シ'], kunyomi: ['つか.う'] },
    { kanji: '便', onyomi: ['ベン', 'ビン'], kunyomi: ['たよ.り'] },
    { kanji: '借', onyomi: ['シャク'], kunyomi: ['か.りる'] },
    { kanji: '働', onyomi: ['ドウ'], kunyomi: ['はたら.く'] },
    { kanji: '兄', onyomi: ['ケイ', 'キョウ'], kunyomi: ['あに'] },
    { kanji: '兆', onyomi: ['チョウ'], kunyomi: ['きざ.す'] },
    { kanji: '入', onyomi: ['ニュウ', 'ジュ'], kunyomi: ['い.る', 'はい.る'] },
    { kanji: '八', onyomi: ['ハチ'], kunyomi: ['や', 'や.つ', 'やっ.つ', 'よう'] },
    { kanji: '六', onyomi: ['ロク', 'リク'], kunyomi: ['む', 'む.つ', 'むっ.つ', 'むい'] },
    { kanji: '具', onyomi: ['グ'], kunyomi: ['そな.える', 'つぶさ.に'] },
    { kanji: '写', onyomi: ['シャ', 'ジャ'], kunyomi: ['うつ.す', 'うつ.る'] },
    { kanji: '冬', onyomi: ['トウ'], kunyomi: ['ふゆ'] },
    { kanji: '切', onyomi: ['セツ', 'サイ'], kunyomi: ['き.る', 'き.れる'] },
    { kanji: '別', onyomi: ['ベツ'], kunyomi: ['わか.れる'] },
    { kanji: '利', onyomi: ['リ'], kunyomi: ['き.く'] },
    { kanji: '前', onyomi: ['ゼン'], kunyomi: ['まえ'] },
    { kanji: '力', onyomi: ['リョク', 'リキ'], kunyomi: ['ちから'] },
    { kanji: '勉', onyomi: ['ベン'], kunyomi: ['つと.める'] },
    { kanji: '動', onyomi: ['ドウ'], kunyomi: ['うご.く', 'うご.かす'] },
    { kanji: '務', onyomi: ['ム'], kunyomi: ['つと.める'] },
    { kanji: '勝', onyomi: ['ショウ'], kunyomi: ['か.つ', 'まさ.る'] },
    { kanji: '化', onyomi: ['カ', 'ケ'], kunyomi: ['ば.ける', 'ば.かす'] },
    { kanji: '北', onyomi: ['ホク'], kunyomi: ['きた'] },
    { kanji: '区', onyomi: ['ク'], kunyomi: [] },
    { kanji: '医', onyomi: ['イ'], kunyomi: [] },
    { kanji: '十', onyomi: ['ジュウ', 'ジッ', 'ジュッ'], kunyomi: ['とお', 'と'] },
    { kanji: '午', onyomi: ['ゴ'], kunyomi: [] },
    { kanji: '半', onyomi: ['ハン'], kunyomi: ['なか.ば'] },
    { kanji: '卒', onyomi: ['ソツ'], kunyomi: [] },
    { kanji: '協', onyomi: ['キョウ'], kunyomi: [] },
    { kanji: '単', onyomi: ['タン'], kunyomi: ['ひとえ'] },
    { kanji: '去', onyomi: ['キョ', 'コ'], kunyomi: ['さ.る'] },
    { kanji: '参', onyomi: ['サン', 'シン'], kunyomi: ['まい.る'] },
    { kanji: '反', onyomi: ['ハン', 'ホン', 'タン'], kunyomi: ['そ.る', 'かえ.す'] },
    { kanji: '取', onyomi: ['シュ'], kunyomi: ['と.る'] },
    { kanji: '口', onyomi: ['コウ', 'ク'], kunyomi: ['くち'] },
    { kanji: '古', onyomi: ['コ'], kunyomi: ['ふる.い'] },
    { kanji: '台', onyomi: ['ダイ', 'タイ'], kunyomi: [] },
    { kanji: '号', onyomi: ['ゴウ'], kunyomi: [] },
    { kanji: '司', onyomi: ['シ'], kunyomi: ['つかさど.る'] },
    { kanji: '同', onyomi: ['ドウ'], kunyomi: ['おな.じ'] },
    { kanji: '向', onyomi: ['コウ'], kunyomi: ['む.く', 'む.ける'] },
    { kanji: '味', onyomi: ['ミ'], kunyomi: ['あじ', 'あじ.わう'] },
    { kanji: '品', onyomi: ['ヒン', 'ホン'], kunyomi: ['しな'] },
    { kanji: '員', onyomi: ['イン'], kunyomi: [] },
    { kanji: '問', onyomi: ['モン'], kunyomi: ['と.う', 'とん'] },
    { kanji: '回', onyomi: ['カイ', 'エ'], kunyomi: ['まわ.る'] },
    { kanji: '図', onyomi: ['ズ', 'ト'], kunyomi: ['はか.る'] },
    { kanji: '国', onyomi: ['コク'], kunyomi: ['くに'] },
    { kanji: '堂', onyomi: ['ドウ'], kunyomi: [] },
    { kanji: '場', onyomi: ['ジョウ'], kunyomi: ['ば'] },
    { kanji: '士', onyomi: ['シ'], kunyomi: [] },
    { kanji: '夏', onyomi: ['カ', 'ゲ'], kunyomi: ['なつ'] },
    { kanji: '夕', onyomi: ['セキ'], kunyomi: ['ゆう'] },
    { kanji: '外', onyomi: ['ガイ', 'ゲ'], kunyomi: ['そと', 'ほか', 'はず.す'] },
    { kanji: '多', onyomi: ['タ'], kunyomi: ['おお.い'] },
    { kanji: '夜', onyomi: ['ヤ'], kunyomi: ['よ', 'よる'] }
];
